In [2]:
import pydicom
from pydicom.pixels import iter_pixels

dicom_data = pydicom.dcmread("Tcga_gbm_ready/b687574c-f30e-45d7-88e5-840968785182.dcm")
ds_pixel_data = dicom_data.pixel_array

In [4]:
import matplotlib.pyplot as plt
import random
import numpy as np
import cv2
    



deneme = ds_pixel_data[random.randint(0, len(ds_pixel_data) - 1)]
cv2.imshow('Original', deneme)
cv2.waitKey(0)

height, width, _ = deneme.shape
start_x = (width - 240) // 2
start_y = (height - 240) // 2


cropped_image = deneme[start_y:start_y+240, start_x:start_x+240]

cv2.imshow('Cropped', cropped_image)
cv2.waitKey(0)

gray_image = cv2.cvtColor(cropped_image, cv2.COLOR_BGR2GRAY)

print(gray_image)

cv2.imshow('Grayscale', gray_image)
cv2.waitKey(0)  

cv2.destroyAllWindows()


    


[[  4   4   4 ... 176 183 189]
 [  4   4   4 ... 156 162 167]
 [  4   4   3 ... 134 140 145]
 ...
 [  2   2   2 ...   1   1   1]
 [  2   2   2 ...   1   1   1]
 [  2   2   2 ...   1   1   1]]


Processing folder: Tcga_lgg_olio_filtered
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 